### ISSUE TITLE
harcoded stuff!

### ISSUE THREAD

**Issue by bacsmar** [elios264/Terrain-Editor#1]
![imagen](https://cloud.githubusercontent.com/assets/7064680/23843869/440b014a-0784-11e7-965e-0fb9db3921e4.png)

**Comment by elios264** [comment]
pues es proyecto personal wey!

            <lcl:ResourceExplorer Grid.Row="2"
                                  Grid.Column="0"
                                  ResourceInfoProviders="{Binding ResourceInfoProviders}"
                                  WorkPath="C:\Users\elios\elios' files" />

no es privado porque no ando pagando.
